[graph]
path = "/graphql"
introspection = true

[csrf]
enabled = false

[trusted_documents]
enabled = false

[telemetry.tracing]
sampling = 1

[mcp]
enabled = true

## Extensions

[extensions.rest]
version = "0.4"

[extensions.nats]
version = "0.4.1"

[[extensions.nats.config.endpoint]]
servers = ["nats://localhost:4222"]

[extensions.postgres]
version = "0.4"

[extensions.postgres.config]
[[extensions.postgres.config.databases]]
# Optional: Specify a name if connecting multiple databases.
# This name links the database connection to a specific subgraph.
name = "default"
url = "postgres://postgres:postgres@localhost:5433/orders_db" # Use environment variables for sensitive parts like passwords


## Dev configuration ##

[subgraphs.orders]
schema_path = "./orders-pg/orders.graphql"

[subgraphs.factories]
schema_path = "./rest-factories/factories.graphql"

[subgraphs.product]
introspection_url = "http://localhost:4000/graphql"
url = "http://localhost:4000/graphql"

[subgraphs.sales]
schema_path = "./sales/sales.graphql"
