[graph]
path = "/graphql"
introspection = true

[csrf]
enabled = false

[trusted_documents]
enabled = false

[telemetry.tracing]
sampling = 1

[cors]
allow_origins = "any"
allow_methods = ["GET", "POST"]
allow_headers = [
    "authorization",
    "content-type",
    "x-grafbase-client-name",
    "x-grafbase-client-version",
    "x-grafbase-telemetry",
]
expose_headers = "any"
max_age = "1d"
